config/routes.rb
Rails.application.routes.draw do
  get '/dashboard',to: "user_panel#index", as: :user_panel
  get 'profile',to: "user_panel#profile",as: :profile
  get 'top_up',to: "user_panel#top_up",as: :top_up
  get 'invites',to: "user_panel#invites",as: :user_invites
  

  resources :leadership_surveys,only: [:new,:create] do
    resources :logbooks
    resources :responses,:controller => "submissions",only: [:new,:create]
  end

  resources :responses,:controller => "submissions",except: [:new,:create] do
    get :results
  end
  

  post 'start_survey',to: "leadership_surveys#start_survey",as: :start_survey
  get 'leadership_assessment/:id',to: "leadership_surveys#leadership_survey",as: :user_survey
  
  # get 'leadership_assessment/:id/results',to: "leadership_surveys#leadership_results",as: :user_survey_results
  
  get 'leadership_assessment/:id/invitees',to: "leadership_surveys#invitees",as: :survey_invitees
  get 'leadership_assessments',to: "leadership_surveys#leadership_tests",as: :user_tests
  post 'invite_user',to: "leadership_surveys#invite_user", as: :invite_user
  delete '/users/:id/destroy', to: 'leadership_surveys#destroy', as: :destroy_test

  # get 'payment',to: "user_panel#payment",as: :payment
  post 'payment',to: "user_panel#payment",as: :payment

  get 'admin_panel',to: 'admin_panel#index',as: :admin_panel
  get 'admin_panel/users',as: :admin_users
  get 'admin_panel/questionnaires',as: :admin_questionnaires
  get 'admin_panel/edit_intro',as: :admin_edit_intro
  post 'edit_intro',to: "admin_panel#edit_intro_save",as: :admin_edit_intro_save

  devise_for :users,:controllers => { sessions: 'users/sessions',registrations: 'users/registrations',passwords: 'users/passwords',invitations: 'users/invitations' }
  resources :users, only: [:edit,:update]

  # get 'personal_logbook', to: 'users#logbook',as: :logbook
  # put 'personal_logbook', to: 'users#save_logbook',as: :save_logbook

  post 'stripe-webhooks',to: 'home#webhooks'

  root 'home#index'
  get 'design', to: 'home#design', as: 'design'

  # Excel Upload Feature
  post '/bulk_users', to: 'admin_panel#bulk_users_upload',
                      as: :bulk_users_upload

  # Payment Feature
  resources :variables

  # Locale Handling
  scope ':locale', locale: /#{I18n.available_locales.join("|")}/ do
    # Questionnaires
    resources :questionnaires
    # Dimensions
    resources :dimensions
    # Questions
    resources :questions
  end
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}")
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :questionnaire
  belongs_to :dimension
  has_many :statements,class_name: "QuestionStatement",dependent: :destroy
  has_many :options,class_name: "QuestionOption",dependent: :destroy

  has_many :submissions,dependent: :destroy

  # after_save :create_children

  accepts_nested_attributes_for :statements, allow_destroy: true,reject_if: proc { |attributes| attributes['full_text'].blank? }
  accepts_nested_attributes_for :options, allow_destroy: true,reject_if: proc { |attributes| attributes['full_text'].blank? }


  # attr_accessor :statements_arr,:options_arr

  # def create_children
  # 	if self.statements_arr.present? and self.questionnaire.name != "Mindset"
  #     self.statements.destroy_all
  # 		self.statements_arr.each do |statement|
  # 			QuestionStatement.create!(question_id: self.id,full_text: statement) if statement.present?
  # 		end
  # 	end

  # 	if self.options_arr.present?
  #     self.options.destroy_all
  # 		self.options_arr.each do |option|
  # 			QuestionOption.create!(question_id: self.id,full_text: option)
  # 		end
  # 	end
  # end
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin
  load_and_authorize_resource
  # GET /questions
  def index
    @questionnaires = Questionnaire.all
    questionnaire = Questionnaire.find(params[:questionnaire]) if params[:questionnaire].present?
    @questionnaire_name = questionnaire&.name
    if params[:questionnaire].present?
      @questions = Question.where(questionnaire_id: questionnaire)
                           .includes(:statements, :options, :dimension)
                           .page(params[:page]).per(25)
    else
      @questions = Question.all.page(params[:page]).per(25)
    end
  end

  # GET /questions/1
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
    @dimensions = []
    @question.statements.build(full_text: 'Where is his/her behaviour currently situated?')
    @question.statements.build(full_text: 'Where do you think it should be to be even more effective as a leader ?')
    # statement1
    2.times do
      @question.options.build
    end
    if request.xhr?
      respond_to do |format|
        format.json {
          if params[:questionnaire_id].present?
            questionnaire = Questionnaire.find(params[:questionnaire_id])
            if questionnaire.id > 2
              statement1 = 'How often does this person shows this behaviour?'
              statement2 = 'How often should this person show this behaviour in order to develop himself as a leader?'
            elsif questionnaire.id == 2
              statement1 = 'Observing the behaviour of this person estimate if the underlying belief is more related to the left hand statement or to the right hand one?'
              statement2 = 'To develop as a leader should this person move more to the right or left hand statement compared with now?'

            else
              statement1 = 'Where is his/her behaviour currently situated?'
              statement2 = 'Where do you think it should be to be even more effective as a leader ?'
            end
            @dimensions = questionnaire.dimensions

            render json: {dimensions: @dimensions,statement1: statement1,statement2: statement2}
          end
        }
      end
    end
  end

  # GET /questions/1/edit
  def edit
    unless @question.statements.present?
      2.times do
        @question.statements.build
      end
    end
  end

  # POST /questions
  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to @question, notice: 'Question was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /questions/1
  def update
    if @question.update(question_params)
      redirect_to @question, notice: 'Question was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /questions/1
  def destroy
    @question.destroy
    redirect_to questions_url, notice: 'Question was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def question_params
      params.require(:question).permit(:questionnaire_id,:dimension_id,statements_attributes: [:id,:_destroy,:statement_type,:full_text],options_attributes: [:id,:_destroy,:full_text,:option_type])
    end
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <% if I18n.locale != :en && form&.object&.id.present?  %>
      <% Globalize.with_locale(:en) do %>
        <p class='mark text-center'>Questionnaire (English: <%= form.object.questionnaire.name %>)<p>
      <% end %>
    <% end %>
    <%= form.select :questionnaire_id,options_for_select(Questionnaire.all.map{|x| [x.name,x.id]},question.questionnaire_id),{include_blank: "Please select a questionnaire type"},{required: true,class: "form-control login-form questionnaire",id: "questionnaire_id"} %>
  </div>
  <div class="form-group">
    <% if I18n.locale != :en && form&.object&.id.present?  %>
      <% Globalize.with_locale(:en) do %>
        <p class='mark text-center'>Dimension (English: <%= form.object.dimension.name %>)<p>
      <% end %>
    <% end %>
    <%= form.select :dimension_id,options_for_select((question&.questionnaire&.dimensions || [])&.map{|x| [x.name,x.id]},question&.dimension_id),{include_blank: "Please select questionnaire first"},{required: true,class: "form-control login-form questionnaire",id: "dimension_id"} %>
  </div>
  
  <div class="statements">
    <% i = 0 %>
    <%= form.fields_for :statements do |statement_fields| %>
      <div class="form-group">
        <% if I18n.locale != :en && form&.object&.id.present?  %>
          <% Globalize.with_locale(:en) do %>
            <p class='mark text-center'>Statement <%= i + 1 %> (English: <%= form.object.statements[i].full_text %>)<p>
          <% end %>
        <% end %>
        <%= statement_fields.text_area :full_text,placeholder: "Statement #{statement_fields.index + 1}", class: 'form-control mb-2' %>
        <%= statement_fields.select :statement_type, QuestionStatement.statement_types.keys, class: 'form-control' %>
      </div>
      <% i += 1 %>
    <% end %>
  </div>
  <div class="options">
    <% j = 0 %>
    <%= form.fields_for :options do |option_fields| %>
      <div class="form-group">
        <% if I18n.locale != :en && form&.object&.id.present?  %>
          <% Globalize.with_locale(:en) do %>
            <p class='mark text-center'>Option <%= j + 1 %> (English: <%= form.object.options[j].full_text %>)<p>
          <% end %>
        <% end %>
        <%= option_fields.text_area :full_text,placeholder: "Option #{option_fields.index + 1}",class: 'form-control mb-2' %>
        <%= option_fields.select :option_type, QuestionOption.option_types.keys%>
      </div>
      <% j += 1 %>
    <% end %>
  </div>
  <div class="actions mt-3">
    <%= form.submit "Save", class: 'btn btn-primary btn-lg btn-block mb-3' %>
    <%= link_to 'Cancel', questions_path,class: "btn btn-secondary btn-lg btn-block mb-3" %>
  </div>
<% end %>

<script>
  $(document).on("turbolinks:load",function() {
    $("#questionnaire_id").change(function(){
      $.ajax({
        url: "/questions/new",
        type: "GET",
        dataType: "json",
        data: {questionnaire_id: $("#questionnaire_id").val()},
        success: function (response) {
          $('#question_statements_attributes_0_full_text').val(response.statement1);
          $('#question_statements_attributes_1_full_text').val(response.statement2);
          var dimensions = response["dimensions"];
          $("#dimension_id").html('<option>Select a dimension</option>');
          for(var i=0; i< dimensions.length; i++){
            $("#dimension_id").append('<option value="' + dimensions[i]["id"] + '">' + dimensions[i]["name"] + '</option>');
          }
        }

      });
    });
  });
</script>

app/views/questions/edit.html.erb
<div class="container-fluid container-top">
  <div class="container container-signin container-sign px-4">
    <div class="modal-login-body">
      <h3 class="text-center mb-4">Editing Question</h3>
      <%= render 'form', question: @question %>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<div class="container-fluid container-admin">
  <ul class="nav nav-tabs nav-tabs-default nav-tabs-centered" id="tabCentered" role="tablist">
    <% @questionnaires.each do |questionnaire| %>
      <li class="nav-item">
        <a class="text-4 nav-link <%= 'active' if questionnaire.id == params[:questionnaire].to_i %>" href="<%= questions_path(questionnaire: questionnaire.id) %>" aria-controls="tab1s" aria-expanded="true"><%= questionnaire.name %></a>
      </li>
    <% end %>
  </ul>
  <div class="pt-4 pb-4">
    <div class="row mb-4 align-items-center">
      <div class="col-lg-9 text-center text-lg-left">
        <h5 class="mb-3 mb-lg-0">Questions of <%= @questionnaire_name.present? ? @questionnaire_name : 'All Questionnaires' %></h5>
      </div>
      <div class="col-lg-3 text-center text-lg-right">
        <%= link_to "Add new question",new_question_path, class:"btn btn-primary mb-2 mb-lg-0" %>
      </div>
    </div>
    <div class="table-responsive table-users">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Questionnaire</th>
            <th>Dimension</th>
            <%# if @questionnaire != "Mindset" %>
              <th>S1</th>
              <th>S2</th>
            <%# end %>
            <th>O1</th>
            <th>O2</th>
            <th colspan="3">
              Actions
            </th>
          </tr>
        </thead>
        <tbody>
          <% @questions.each do |question| %>
            <tr>
              <td><%= question&.questionnaire&.name %></td>
              <td><%= question&.dimension&.name %></td>
              <%# if @questionnaire != "Mindset" %>
                <% if question.statements.present?%>
                  <% question.statements.each do |statement|%>
                    <td><%= statement&.full_text&.truncate(150) %></td>
                  <% end %>
                <% else %>
                  <td></td><td></td>
                <% end %>
              <% #end %>
              <% if question.options.present?%>
                <% question.options.each do |option|%>
                  <td><%= option&.full_text&.truncate(150) %></td>
                <% end %>
              <% else %>
                <td></td><td></td>
              <% end %>
              <td class="action-links"><%= link_to '<i class="fas fa-eye"></i>'.html_safe, question %></td>
              <td class="action-links"><%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_question_path(question) %></td>
              <td class="action-links"><%= link_to '<i class="fas fa-trash-alt text-danger"></i>'.html_safe, question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <center><%= paginate @questions %></center> 
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="container-fluid container-top">
  <div class="container container-signin container-sign px-4">
    <div class="modal-login-body">
      <h3 class="text-center mb-4">New Question</h3>
      <%= render 'form', question: @question %>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<div class="container-fluid container-admin">
  <div class="container container-signup container-sign px-4">
    <div class="modal-login-body">
      <h3 class="text-center mb-3">Question Details</h3>
      <div class="table-responsive">
        <table class="table table-bordered">
          <tr>
            <th>
              Questionnaire:
            </th>
            <td>
              <%= @question&.questionnaire&.name %>
            </td>
          </tr>
          <tr>
            <th>
              Dimension:
            </th>
            <td>
              <%= @question&.dimension&.name %>
            </td>
          </tr>
          <% @question.statements.each_with_index do | statement,index|  %>
	          <tr>
	            <th>
	              Statement <%= index + 1 %>
	            </th>
	            <td>
	              <%= @question&.dimension&.name %>
	            </td>
	          </tr>
	          <tr>
	            <th>
	              Type
	            </th>
	            <td>
	              <%= statement.statement_type%>
	            </td>
	          </tr>
	        <% end %> 
	        <% @question&.options&.each_with_index do | option,index|  %> 
	        	<tr>
	            <th>
	              Option <%= index + 1%>
	            </th>
	            <td>
	              <%= option&.full_text %>
	            </td>
	          </tr>
	          </tr>
	            <th>
	              Option <%= index + 1%> Type
	            </th>
	            <td>
	              <%= @question&.dimension&.name %>
	            </td>
	          </tr>
	        <% end %>
        </table>
        <center>
					<%= link_to 'Edit', edit_question_path(@question), class:"btn btn-primary btn-lg mb-3" %> 
					<%= link_to 'Back', questions_path, class:"btn btn-secondary btn-lg mb-3" %>
				</center>
      </div>
    </div>
  </div>
</div>